{% set name = "nc2zarr" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bcdev/nc2zarr/archive/v{{ version }}.tar.gz
  sha256: 9aa981128590436ee0d4fb2f23c4cc7b1a76ba30d1b8ddf2d2cac9263a89abdf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - nc2zarr = nc2zarr.cli:nc2zarr

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click
    - dask
    - fsspec
    - netcdf4
    - numpy
    - pandas
    - pyyaml
    - retry
    - s3fs
    - xarray
    - zarr

test:
  imports:
    - nc2zarr
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests
    - nc2zarr --help

about:
  home: https://github.com/bcdev/nc2zarr
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python tool that converts NetCDF files to Zarr format
  description: |
    nc2zarr reads one or more NetCDF datasets and writes or appends them
    to a single Zarr output dataset.
  doc_url: https://github.com/bcdev/nc2zarr/blob/main/README.md
  dev_url: https://github.com/bcdev/nc2zarr

extra:
  recipe-maintainers:
    - bcdev
    - pont-us
    - forman
    - AliceBalfanz
    - dzelge
    - TonioF
