{% set name = "nc2zarr" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bcdev/nc2zarr/archive/v{{ version }}.tar.gz
  sha256: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - nc2zarr = nc2zarr.cli:nc2zarr

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - click
    - dask
    - fsspec
    - netcdf4
    - numpy
    - pandas
    - pyyaml
    - retry
    - s3fs
    - xarray
    - zarr

test:
  imports:
    - nc2zarr
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pytest tests
    - nc2zarr --help

about:
  home: https://github.com/bcdev/nc2zarr
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python tool that converts NetCDF files to Zarr format
  description: |
    nc2zarr reads one or more NetCDF datasets and writes or appends them
    to a single Zarr output dataset.
  doc_url: https://github.com/bcdev/nc2zarr/blob/main/README.md
  dev_url: https://github.com/bcdev/nc2zarr

extra:
  recipe-maintainers:
    - AliceBalfanz
    - b-yogesh
    - forman
    - konstntokas
    - pont-us
    - TejasMorbagal
    - thomasstorm
    - TonioF
